# Generated by Django 3.2.5 on 2021-07-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.IntegerField(default=0)),
                ('shop', models.URLField(default='')),
                ('type', models.CharField(choices=[('홈데코/조명', '홈데코/조명'), ('DIY/공구', 'DIY/공구'), ('가구', '가구'), ('패브릭', '패브릭'), ('가전', '가전'), ('수납/정리', '수납/정리')], max_length=20)),
            ],
        ),
    ]
