# Generated by Django 3.2.5 on 2021-07-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('수납/정리', '수납/정리'), ('가구', '가구'), ('가전', '가전'), ('패브릭', '패브릭'), ('DIY/공구', 'DIY/공구'), ('홈데코/조명', '홈데코/조명')], max_length=20),
        ),
    ]
