# Generated by Django 3.2.5 on 2021-07-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtom', '0002_alter_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('패브릭', '패브릭'), ('홈데코/조명', '홈데코/조명'), ('가구', '가구'), ('DIY/공구', 'DIY/공구'), ('수납/정리', '수납/정리'), ('가전', '가전')], max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mtom.Tag'),
        ),
    ]
